### ISSUE TITLE
Pull-Request for MessageCommunicator

### ISSUE THREAD

**Issue by Pinny93** [RolandKoenig/MessageCommunicator#1]
Hello Roland,

I made a feature for selecting Send Mode (HEX, Unicode or ASCII) on sending of Messages.
I tried to make a pull request, but its not possible to create one directly in the main branch. So can you please create a feature branch for me? Thank you.

Here is a Preview of the Feature:
https://cloud.jp-net.eu/index.php/s/RjCPAc4pPixo3TS

Best regards,
Pinny93

**Comment by RolandKoenig** [comment]
Hello Pinny93

Thank you for your work :-)
Did you check the last releases? I've also implemented that feature in the last weeks, see here in current release 0.6.0

![2020-12-27_18-53-27](https://user-images.githubusercontent.com/11254388/103176783-0f4cd880-4875-11eb-8777-b1120bc56c8e.png)

Greetings
Roland

**Comment by Pinny93** [comment]
Thank you for your answer, I had indeed an older version of the project.
So I now cloned the current Version an the feature works fine.

Unfortunatly, the pull-requests do still not work on the main branch, so I made a Fork on my Account:  Pinny93 /
MessageCommunicator 
For my protocol testing purposes I made a new "RawMessageRecognizer" which just transmits the bytes as-is.
I do not need the start/end symbol stuff as I simply type the whole header of the protocol into the send text box.
![grafik](https://user-images.githubusercontent.com/8857937/103205103-1ae1e300-48f9-11eb-8853-0d9e51de7625.png)
Now the app works fine for me for now.
Thank you for developing this great project.

Greetings
Pinny93

**Comment by RolandKoenig** [comment]
Thank you for your feedback
Currently I'm working on an integrated documentation. Also I want to integrate a short check for newer releases on startup.

What you write about pull-requests seems strange. I see the fork on your account but the MessageCommunicator project site don't lists it. I will look into this
